services:
  - type: web
    name: address-converter
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:0EyXMcJrOEneeocF8fDGJuMEmvOcPmzZM0P/9884RnQ=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: SUPZJWXcqVyvkcbHHbnqsDaHcMERxZDp
