services:
  - type: web
    name: address-converter
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        key: base64:0EyXMcJrOEneeocF8fDGJuMEmvOcPmzZM0P/9884RnQ=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_DATABASE
        value: location
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
